### ISSUE TITLE
Form usage

### ISSUE THREAD

**Issue by w3z315** [jacoweb/freelanceTheme#1]
Hello!

Is the contact form functionable?
If yes, how do I use it?

Thank you !

**Comment by jacoweb** [comment]
Hi there! Sorry for late reply, but yes the form is functionable, but you need to install some plugins to get it work.

Download octomail:
http://octobercms.com/plugin/octodevel-octomail

Check the readme, you will fix it ;)

**Comment by hannylicious** [comment]
Octomail is no longer a plugin - is the contact form useless?

**Comment by jacoweb** [comment]
You can still get it from here:
https://github.com/ChadStrat/octomail
